### ISSUE TITLE
`symengine.S(1.) == 1` gives False

### ISSUE THREAD

**Issue by mlangiu** [symengine/symengine#1709] opened 2020-11-11 09:11 UTC
When trying to work around #1708, I discovered:

```python
for backend in sympy, symengine:
    print(f'{backend.S(1) == 1 = }')
    print(f'{backend.S(1.) == 1 = }')
```    

gives

```python
backend.S(1) == 1 = True
backend.S(1.) == 1 = True
backend.S(1) == 1 = True
backend.S(1.) == 1 = False
```

i.e. implicit casting to int doesn't seem to happen in Symengine while it does in Sympy, is this intended?

_Originally posted by @mlangiu in https://github.com/symengine/symengine/issues/681#issuecomment-724043976_

**Comment by rikardn** [comment] 2020-11-12 18:47
Both sympy and symengine create floats for the "1." case:

```python
import symengine
import sympy

print(type(symengine.S(1.)))
print(type(sympy.S(1.)))
```

gives

```
<class 'symengine.lib.symengine_wrapper.RealDouble'>
<class 'sympy.core.numbers.Float'>
```

The difference is in the equality comparison

```python
> symengine.Eq(symengine.S(1.), 1)
False
> symengine.Eq(symengine.S(1.), 1.)
True
```

I don't know if it would give any problems if letting `S(1.)` return `Integer(1)`

**Comment by isuruf** [comment] 2020-11-12 18:53
Thanks @mlangiu for the report and @rikardn for having a look. As @rikardn mentioned they both return floats, but the difference is in the equality comparison. In SymEngine for structural equality, we made a deliberate choice to make floats and integers compare differently.

For example,
```
In [1]: from sympy import *

In [2]: sin(S(1.))
Out[2]: 0.841470984807897

In [3]: sin(S(1))
Out[3]: sin(1)

In [4]: from symengine import *

In [5]: sin(S(1.))
Out[5]: 0.841470984807897

In [6]: sin(S(1))
Out[6]: sin(1)
```
which I think explains the difference between float 1 and integer 1. So they are obviously not equal in sympy, but compare equally which I wanted to avoid in symengine.

**Comment by rikardn** [comment] 2020-11-12 20:37
I can understand the rationale for this design decision. If we see floats (or RealDouble) as approximated real numbers this makes sense. See for example https://github.com/sympy/sympy/issues/20364 and https://github.com/sympy/sympy/pull/20033 for further discussions.

**Comment by rikardn** [comment] 2020-12-05 13:38
Closing since this is by design

**Closed by rikardn** 2020-12-05 13:38 UTC
