### ISSUE TITLE
Parsing mistake with "z + f(x + y, g(x), h(g(x)))"?

### ISSUE THREAD

**Issue by Marlin-Na** [symengine/symengine#1447] opened 2018-07-19 21:14 UTC
This is what I got from the python wrapper:

```
>>> from symengine import S
>>> S("z + f(x + y, g(x), h(g(x)))")
h(g(x))
```

**Comment by isuruf** [comment] 2018-07-19 21:16
Duplicate of https://github.com/symengine/symengine/issues/1444

**Closed by isuruf** 2018-07-19 21:16 UTC
