### ISSUE TITLE
Where is the user documentation

### ISSUE THREAD

**Issue by sylvaticus** [symengine/symengine#1222] opened 2017-03-08 17:56 UTC
Hello, 
 I can't find the user documentation (the doc folder seems to be a template ?? )

Also, why in the project description there is a link to SymPy ? In the SymPy project page it is stated that SymPy is written totally in python..

**Comment by ShikharJ** [comment] 2017-03-09 08:53
Hi @sylvaticus 
Unfortunately, there is no proper documentation currently available for `SymEngine`.
This project was initially developed to serve as a symbolic backend for the `SymPy` CAS, for speeding up symbolic computations. So basically, `SymEngine` is a rewrite of core parts of `SymPy` in C++. Though a large number of features implemented in `SymPy` are also available in `SymEngine`, still it lags a lot behind `SymPy` featurewise.

**Comment by isuruf** [comment] 2017-03-29 16:48
Duplicate of #1081

**Closed by isuruf** 2017-03-29 16:48 UTC
