### ISSUE TITLE
console crashes with symengine v0.4.1

### ISSUE THREAD

**Issue by raphaelquast** [symengine/symengine#1578] opened 2019-07-31 10:22 UTC
Problem:
if I install `python-symengine v0.4.0` together with `symengine v0.4.1` (as is done automatically if you do `conda install -c conda-forge python-symengine`) the python-console crashes everytime i run a code that involves symengine without any warning whatsoever.

after downgrading to `symengine v0.4.0` everything works as expected again.

is it possible that the python-symengine bindings need an update to work with `symengine v0.4.1` ?

**Comment by raphaelquast** [comment] 2019-08-01 06:19
OK, thanks for having a look!

**Comment by rikardn** [comment] 2021-11-02 13:55
I am closing since this issue was filed against an old version of symengine. If the problem is still present in the latest version feel free to reopen this.

**Closed by rikardn** 2021-11-02 13:55 UTC
