### ISSUE TITLE
Implement Julia wrappers

### ISSUE THREAD

**Issue by certik** [symengine/symengine#150] opened 2014-04-18 02:14 UTC
We need to fix #149 (C wrappers) first for this. Then the Julia wrapper would just call this using `ccall` and provide some nicer Julia interface.

**Comment by jcrist** [comment] 2015-02-26 06:03
In my spare time, I've been playing around with implementing a [CAS in Julia](https://github.com/jcrist/Juniper.jl). I've spent a bit of time optimizing it, and I think it's about as fast as it could be with the current state of Julia compiler. All I really care about is differentiation of large expressions (dynamics stuff), so I tried a few simple benchmarks, and Csympy came out ~1-5 times faster than my code (and mine uses cacheing!). I'd like to get a wrapper for Csympy going so I can start using that instead. I saw the C wrappers have been implemented, so this shouldn't be too difficult. Would you want the wrapper to live in this repo, or in a separate one? Most Julia packages exist as their own repo.

**Comment by isuruf** [comment] 2015-02-26 07:09
It's easier to maintain if we use the same repo right? Is there any reason against using the same repo?

Btw, you'll need to build csympy as a shared library. See #360
I started writing a wrapper here https://gist.github.com/isuruf/cb4f16d05b7266de227b, but that was for the previous api and wasn't updated after the changes in #366. I will look at it later today.

**Comment by jcrist** [comment] 2015-02-26 07:19
Packaging is the main issue. The Julia package manager is git based, and expects packages to have a certain file structure. In cases where the package is a wrapper to some library, that code is usually pulled in from a separate repo.

I built csympy as a shared library, but am getting a weird undefined symbol error upon calling `dlopen`:

```ERROR: could not load module /home/jimmy/Code/csympy/src/libcsympy.so: /home/jimmy/Code/csympy/src/libcsympy.so: undefined symbol: _ZN7Teuchos19ActiveRCPNodesSetupD1Ev
 in dlopen at ./c.jl:28```

I tried building with and without Teuchos RCP (at least I think that's what the cmake options were), and get the same error either way. Not sure what the issue is here.

**Comment by certik** [comment] 2015-02-26 07:27
You need to link with `-lcsympy -lteuchos` I think. You need to use csympy's RCP, otherwise it won't work. We can get rid of Teuchos, we only use the stacktrace stuff (which is independent of it) and for testing that we follow the `Teuchos::RCP` interface, but that we can do on Travis by installing Teuchos from Trilinos (our some separate repository).

@jcrist I looked at your Julia code --- are you sure you use the same algorithms? You might be using inefficient algorithms. How do you represent Add and Mul?

**Comment by certik** [comment] 2015-02-26 07:28
We can create a separate repository for the Julia wrappers, that's fine. We can use git submodule to track which exact csympy version works with the wrappers.

**Comment by Upabjojr** [comment] 2015-02-26 10:30
By the way, there's another developer working on a CAS in Julia:
https://github.com/jlapeyre/SJulia

His purpose is to have a Mathematica-compatible CAS. It already has bindings to SymPy to provide the missing algorithms. There is already a Mathematica-compatible pattern matcher.

**Comment by pbrady** [comment] 2015-02-26 16:16
I've also used https://github.com/johnmyleswhite/Calculus.jl to perform some symbolic operations.   I think the neat thing about the above approach is the heavy use of dispatching on the 'head' of an expression which avoids a lot of if statements and such.  @jcrist have you looked into this kind of implementation?  I'm wondering if it might be faster.  In julia 0.4 (I think) they're implementing value based dispatch as well which looks like it would work well with your head structure being Int8's.

**Comment by certik** [comment] 2015-02-26 16:51
There is also a thread in Julia about this:  https://groups.google.com/d/msg/julia-users/jP1VlOe80HQ/e4KzNARuI9AJ, I posted there about CSymPy.

**Comment by Upabjojr** [comment] 2015-02-26 18:08
> In julia 0.4 (I think) they're implementing value based dispatch as well which looks like it would work well with your head structure being Int8's.

@pbrady I think you had a similar idea to what I thought:
https://github.com/jcrist/Juniper.jl/issues/1

The trick is that Julia allows to use instances of types as parametric types.

Anyways, the point now is, should the two implementations (Juniper and SJulia) be unified or continued as separate ones? SJulia looks much like a clone of Mathematica, with the real pain that you need two different tree nodes for commutative and non-commutative multiplications (I love SymPy because it allows mixed commutative and non-commutative parts in Mul, and this is great for Quantum Mechanics, matrix algebra, modern physics, etc... ).

**Comment by Upabjojr** [comment] 2015-02-26 18:10
@isuruf do you know about [Cxx.jl](https://github.com/Keno/Cxx.jl) ? It looks promising, and may avoid a lot of work if it is included into Julia.

**Comment by jcrist** [comment] 2015-02-26 18:40
> I think the neat thing about the above approach is the heavy use of dispatching on the 'head' of an expression which avoids a lot of if statements and such. @jcrist have you looked into this kind of implementation?

> @pbrady I think you had a similar idea to what I thought:
jcrist/Juniper.jl#1

See my reply [here](https://github.com/jcrist/Juniper.jl/issues/1#issuecomment-76235184). The issue is that Julia can't generate native code when the *concrete* type isn't known at compile time. This means that such an approach results in dynamic method lookup, which is slow (and allocates a ton more memory). Dispatching on `Val` types is the same way (requires a dynamic lookup).

I do use some of the benefits of the dispatch system, for example:

```
expr = a + b + c + d*e +sin(f)
```
is converted at compile time into:

```
expr = Add([a, b, c, Mul([d, e]), sin(f))
```
which removes the need to create intermediate expressions for `a + b`, `a + b + c`, etc...

**Comment by jcrist** [comment] 2015-02-26 18:45
> @jcrist I looked at your Julia code --- are you sure you use the same algorithms? You might be using inefficient algorithms. How do you represent Add and Mul?

All function nodes (anything that isn't a leaf) store their arguments in a `Vector{Symbolic}`. I saw CSymPy uses a hashtable instead, I assume this is to remove the need to repeatedly build up a dict of coefficients/exponents for canonicalizing `Add`/`Mul`? Unfortunately, Julia's hashtables are a bit heavy, so that may not result in speed gains here. I'm not sure.

Anyway, to keep this thread from being brought off topic, why don't we move all discussion of `Juniper` to the [Juniper repo](https://github.com/jcrist/Juniper.jl).

> You need to link with -lcsympy -lteuchos I think.

Thanks, I'll try that and report back.

**Comment by isuruf** [comment] 2015-03-03 16:29
@jcrist, can you check with the latest master? (using dlopen with csympy lib path should work. And if the library is in the LD_LIBRARY_PATH, dlopen is also not necessary)

**Comment by certik** [comment] 2015-03-03 16:37
Build with `-DBUILD_SHARED_LIBS=on`, to get a shared library. The `teuchos` lib should be included in the shared library, so no need to worry about it anymore.

**Comment by isuruf** [comment] 2015-06-08 04:18
@jcrist We started Julia wrappers here https://github.com/symengine/SymEngine.jl.

**Comment by isuruf** [comment] 2015-10-19 19:00
Closing this as we have basic wrapper code in above repository.

**Closed by isuruf** 2015-10-19 19:00 UTC
Labels: enhancement
