### ISSUE TITLE
If a sum is subtracted, merge it into the resulting sum

### ISSUE THREAD

**Issue by Wrzlprmft** [symengine/symengine#1347] opened 2017-10-22 10:36 UTC
It seems that subtracting `expr` is realised as and addition of `Mul(-1,expr)`, which in turn does not means that if the subtrahend is a sum, it will not be merged in the sum resulting from the subtractions. This yields an overcomplication of certain terms that do not get simplified automatically. For example `x - (1 + x)` stays like this and does not get automatically reduced to `-1`.

**Comment by isuruf** [comment] 2017-10-22 15:31
Duplicate of https://github.com/symengine/symengine/issues/207

**Closed by isuruf** 2017-10-22 15:31 UTC
