### ISSUE TITLE
any documents for beginners?

### ISSUE THREAD

**Issue by tilneyyang** [symengine/symengine#1718] opened 2020-12-03 11:53 UTC
Somebody told me this library is the right one to solve polynomial factorization and equation systems. The python counterpart Sympy seems to be very powerful.  After some painful time going through the codes/testcases of C++ SymEngine and the underlying library Flint, I still don't have a very clear idea about what is this library capable of.

Is there any documents/hints for  beginners other than basic interactive c++ example?  Most of the test cases in the test dir is not readable. 

Thanks!

**Comment by rikardn** [comment] 2020-12-03 12:17
This is a duplicate of #1081

There is a little documentation available at the webpage https://symengine.github.io

Since symengine is meant to be both a standalone library and to fit as a fast core for sympy I would advice you to first try sympy and see if what you want to do is available there. Next you could try the symengine python package which should have a similar API.

**Closed** 2020-12-05 11:22 UTC
Labels: documentation, question
